#!/bin/bash
TOTAL=`cat /var/log/nginx/access.log | wc -l`

for i in HIT EXPIRED MISS UPDATING
do
    NOME="SUM_$i"
    NUMERO=$(grep $i /var/log/nginx/access.log | wc -l)
    VALOR=$(expr $NUMERO \* 100 / $TOTAL)
    echo "$NOME = $NUMERO | $VALOR%"
done

echo TOTAL = $TOTAL

